apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-liao-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: 192.168.3.207:5000/fft/postgres:v1.7
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
  - name: tcp
    nodePort: 10351
    port: 5432
    protocol: TCP
    targetPort: 5432